
name: Deployment

on:
  push:
    branches:
      - master
      - feature/*


env:
  ENV: "prod"
  OU: "compliance"
  ACCOUNT: "data_archive"
  TF_VERSION: "1.5.7"
  APPLY: "false"

jobs:
  plan:
    environment: plan
    runs-on: lnw-runners-extra

    strategy:
      matrix:
        deploy: [
          { instance: fft, region: eu-central-1 },
          { instance: use, region: us-east-1 },
          { instance: can, region: ca-central-1 },
          { instance: mil, region: eu-south-1 },
        ]

    steps:
      - name: Checkout ${{ matrix.deploy.instance }}
        uses: actions/checkout@v4

      - name: Set Apply Flag ${{ matrix.deploy.instance }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "APPLY=true" >> $GITHUB_ENV

      - name: Run terraform ${{ matrix.deploy.instance }}
        id: terraform
        uses: #action.yml repo/module
        with:
          OU: ${{ env.OU }}
          ACCOUNT: ${{ env.ACCOUNT }}
          ENVIRONMENT: ${{ env.ENV }}
          INSTANCE: ${{ matrix.deploy.instance }}
          AWS_REGION: ${{ matrix.deploy.region }}
          TF_VERSION: ${{ env.TF_VERSION }}
          TF_SPOKE_AWS_ACCESS_KEY_ID: ${{ secrets.TF_SPOKE_AWS_ACCESS_KEY_ID }}
          TF_SPOKE_AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_SPOKE_AWS_SECRET_ACCESS_KEY }}
          APPLY: ${{ env.APPLY }}